### ISSUE TITLE
Add a settings page to the Gutenberg Forms submenu

### ISSUE THREAD

**Issue by paaljoachim** [munirkamal/gutenberg-forms#100]
Add a Settings page below Entires submenu.

1. Default submission admin e-mail address and other e-mail addresses.
2. Import/export a Gutenberg Form.

3. Where the user can optionally move the Gutenberg Forms sidebar menu item to below WP Settings. Many plugins add their settings pages either inside the WP Settings area or just below the WP Settings option. Keeping WordPress core menu items above Settings and plugin sidebar items below.

4. I am thinking there might also be other options one would like to add directly to a settings page.

**Comment by munirkamal** [comment]
I think we already have an admin page now which is currently just showing a quick rough intro video with some content and links. We will utilize this page to include settings, integrations, etc as a single admin page.

Regarding the settings you suggested.

1) The default submission is already used as the admin email of the website for all forms. Why would we need this option then?

2) Import/Export is also possible already, but yeah we can have options to make it easier for users. This is good to have.

3) I don't see this practical. Because within our menu we currently have 3 things. 1 admin page and 2 CPTs (Forms & Entries). This cannot be moved under the settings menu as far as I understand.

So the Import/Export option is something sounds good to me, and will be added.

Cheers.

**Comment by munirkamal** [comment]
Closing this issue as created another for the import/export feature.

**Comment by paaljoachim** [comment]
Better explanation...

> The default submission is already used as the admin email of the website for all forms. Why would we need this option then?

If I understand this correctly one has to click the mail builder icon and add an e-mail address, or do one not need to add an e-mail address as the form will automatically send the submission to the site admin e-mail address?

> I don't see this practical. Because within our menu we currently have 3 things. 1 admin page and 2 CPTs (Forms & Entries). This cannot be moved under the settings menu as far as I understand.

I appologize for the misunderstanding.
What about giving the option to move the Gutenberg Forms top menu + submenu to a top menu below the settings (not inside settings)? Or just skip it for now. I just like to in general have all plugins add a section below the WordPress core areas.

Similar to how the the Gutenberg plugin has an area below Settings here:
![Screen Shot 2020-04-14 at 13 41 33](https://user-images.githubusercontent.com/5323259/79221274-d17a6200-7e55-11ea-847f-585ecea74580.png)

**Comment by munirkamal** [comment]
`If I understand this correctly one has to click the mail builder icon and add an e-mail address, or do one not need to add an e-mail address as the form will automatically send the submission to the site admin e-mail address?`

Yes, it automatically sends it to the admin by default. Even if you don't add an email address.

`What about giving the option to move the Gutenberg Forms top menu + submenu to a top menu below the settings (not inside settings)? Or just skip it for now. I just like to in general have all plugins add a section below the WordPress core areas.`

We can do it, but I like to keep it where it is now. Let's see if this is something more users get bothered with, so we can move it then.
