### ISSUE TITLE
Creating a Form. Not showing up in the Gutenberg Forms -> Forms page.

### ISSUE THREAD

**Issue by paaljoachim** [munirkamal/gutenberg-forms#96]
I create a form on the contact page.
Give it a Form Label: Contact Form.

<img width="1286" alt="Screen Shot 2020-04-13 at 21 30 13" src="https://user-images.githubusercontent.com/5323259/79153329-fa571480-7dcd-11ea-8567-abafda8f3fd7.png">

I expect the Contact Form to show up under Gutenberg Forms (WP sidebar menu) -> Forms.
But it does not show up. The Forms area is empty.

<img width="994" alt="Screen Shot 2020-04-13 at 21 30 48" src="https://user-images.githubusercontent.com/5323259/79153389-10fd6b80-7dce-11ea-800e-3d07c2b64c0c.png">

**Comment by munirkamal** [comment]
@paaljoachim 

This will not. Both are different ways to create forms. You can either create it via the Forms CPT so that you can use it anywhere using a shortcode. 

Or you can create forms as you have been doing directly via the post/page in Gutenberg editor.

I hope this makes sense?

**Comment by paaljoachim** [comment]
I understand the separation but it would be great if we could have a way to communicate between the two. 

One thing that can be adjusted is previewing the shortcode in the backend. So one can see the form. Then have for instance an edit icon in the toolbar. Clicking it leads one to the Forms screen and editing the form. Etc.

**Comment by munirkamal** [comment]
Yeah, the shortcode approach in the Gutenberg Editor will ultimately be improved with something like you are suggesting. That is already in mind. So, yes this is something already in my mind. 

I need to figure out how the reusable blocks system works for a custom CPT like ours. So that way both options will communicate better. A user may create a form and add to "Saved Forms" as you add to Reusable Blocks. But, I didn't yet figure how to achieve it.

**Comment by paaljoachim** [comment]
Reusable blocks also need a good improvement in Gutenberg Core. 

Ok I will go ahead and close this issue for now. We can always reopen at a future time.
